#ifndef MACRO_H_
#define MACRO_H_

#define CLIENTAREA_WIDTH 500
#define CLIENTAREA_HEIGHT 800
#define WINDOWS_BACKGROUND_COLOR RGB(240,240,240)

#define IDM_SELECT_FILES 101
#define IDM_START_TALKING 103
#define IDM_STOP_TALKING 104

#define TEXTBOX_MAIN_X 5
#define TEXTBOX_MAIN_Y 5
#define TEXTBOX_MAIN_W 490
#define TEXTBOX_MAIN_H 300

#define LISTBOX_FILES_X 5
#define LISTBOX_FILES_Y 425
#define LISTBOX_FILES_W 200
#define LISTBOX_FILES_H 370

#define BUTTON_SELECT_FILES_X 300
#define BUTTON_SELECT_FILES_Y 500

#define BUTTON_START_TALKING_X 100
#define BUTTON_START_TALKING_Y 350

#define BUTTON_STOP_TALKING_X 300
#define BUTTON_STOP_TALKING_Y 350

#define BUTTON_WIDTH 100
#define BUTTON_HIGHT 25




#endif
